

condors_tn_mall_homepageNewProd:
    path:     /
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:showNewProduct }

condors_tn_mall_contact:
    path:     /contact
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:showContact }
  
condors_tn_mall_shopDetail:
    path:     /shop-Detail/{id}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:shopDetail }
    requirements:
        id: \d+


condors_tn_mall_account:
    path:     /user/account
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:myAccount}
    

condors_tn_mall_pro_regsitration:
    path:     /responsable/register
    defaults: { _controller: CondorsTnMallBundle:Registration:registerBrand}
    
 
 
condors_tn_mall_regsitration:
    path:     /register
    defaults: { _controller: CondorsTnMallBundle:Registration:registerUser}
    
    
condors_tn_mall_responsable_index:
    path:     /user-responsable/Dashboard
    defaults: { _controller: CondorsTnMallBundle:Responsable:index}

condors_tn_mall_responsable_produit:
    path:     /user-responsable/products
    defaults: { _controller: CondorsTnMallBundle:Responsable:products}
    

condors_tn_mall_responsable_produit_midifier:
    path:     /user-responsable/products/modify/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:modify}
    requirements:
        id: \d+
        
condors_tn_mall_responsable_produit_delete:
    path:     /user-responsable/products/delete/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:delete}
    requirements:
        id: \d+
   
condors_tn_mall_responsable_produit_searchProd:
    path:     /user-responsable/products/searchProd/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:Responsable:searchProd}


condors_tn_mall_simpleUser_produit_searchProdOrder:
    path:     /brands/mini-website/{id}/products/searchProdOrder/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:searchProdSimpleOrder}
    requirements:
        id: \d+


    
#Brands

condors_tn_mall_responsable_brands:
    path:     /user-responsable/brands
    defaults: { _controller: CondorsTnMallBundle:Responsable:brands}
    
    
condors_tn_mall_simple_brands:
    path:     /brands
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:brands}
    
condors_tn_mall_simple_brands_special:
    path:     /brands/mini-website/{id}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:brandsSpec}
    requirements:
        id: \d+

#Categories

condors_tn_mall_responsable_categories:
    path:     /user-responsable/categories
    defaults: { _controller: CondorsTnMallBundle:Responsable:categories}

condors_tn_mall_responsable_categories_update_pos:
    path:     /user-responsable/categories/update/{id}/{pos}
    defaults: { _controller: CondorsTnMallBundle:Responsable:updateCatPosition}


condors_tn_mall_simple_categories_searchCategories:
    path:     /categories/search-categories/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:Responsable:searchCategorie}
    requirements:
        txtSearch: \d+

condors_tn_mall_check-google:
    path:     /login/check-google
    defaults: { _controller: CondorsTnMallBundle:Responsable:checkGoogle}
    
  #AMIN SECTION DON'T TOUCH OR I'LL KILL YOU! 
  
condors_tn_mall_responsable_categories_update_pos:
    path:     /user-responsable/categories/update/{id}/{pos}
    defaults: { _controller: CondorsTnMallBundle:Responsable:updateCatPosition}
  
condors_tn_mall_Admin_index:
    path:     /admin
    defaults: { _controller: CondorsTnMallBundle:Admin:index }
    
condors_tn_mall_Admin_GestionPack:
    path:     /admin/pack
    defaults: { _controller: CondorsTnMallBundle:Admin:gestionPack }
    
condors_tn_mall_Admin_addPack:
    path:     /admin/pack/add
    defaults: { _controller: CondorsTnMallBundle:Admin:addPack }

condors_tn_mall_Admin_modifyPack:
    path:     /admin/pack/modify/{id}
    defaults: { _controller: CondorsTnMallBundle:Admin:modifyPack }

condors_tn_mall_Admin_displayPacks:
    path:     /admin/pack/display
    defaults: { _controller: CondorsTnMallBundle:Admin:displayPacks }

condors_tn_mall_Admin_removePacks:
    path:     /admin/pack/remove/{id}
    defaults: { _controller: CondorsTnMallBundle:Admin:removePack }

condors_tn_mall_Admin_test:
    path:     /test
    defaults: { _controller: CondorsTnMallBundle:Admin:test }
    
condors_tn_mall_responsable_displayBouthPacks:
    path:     /user-responsable/displayBoughtPacks
    defaults: { _controller: CondorsTnMallBundle:Responsable:displayBouthPacks}
    
condors_tn_mall_responsable_GestionPack:
    path:     /user-responsable/managePacks
    defaults: { _controller: CondorsTnMallBundle:Responsable:gestionPack }
    
condors_tn_mall_responsable_buyPack:
    path:     /user-responsable/buyPacks/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:buyPacks }
 
 #END AMIN YOU CAN TOUCH EVERY THING AFTER HERE !
