

condors_tn_mall_homepageNewProd:
    path:     /
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:showNewProduct }
  
condors_tn_mall_shopDetail:
    path:     /shop-Detail/{id}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:shopDetail }
    requirements:
        id: \d+


condors_tn_mall_account:
    path:     /user/account
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:myAccount}
    

condors_tn_mall_pro_regsitration:
    path:     /responsable/register
    defaults: { _controller: CondorsTnMallBundle:Registration:registerBrand}
    
 
 
condors_tn_mall_regsitration:
    path:     /register
    defaults: { _controller: CondorsTnMallBundle:Registration:registerUser}
    
    
condors_tn_mall_responsable_index:
    path:     /user-responsable/Dashboard
    defaults: { _controller: CondorsTnMallBundle:Responsable:index}

condors_tn_mall_responsable_produit:
    path:     /user-responsable/products
    defaults: { _controller: CondorsTnMallBundle:Responsable:products}
    

condors_tn_mall_responsable_produit_midifier:
    path:     /user-responsable/products/modify/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:modify}
    requirements:
        id: \d+
        
condors_tn_mall_responsable_produit_delete:
    path:     /user-responsable/products/delete/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:delete}
    requirements:
        id: \d+
   
condors_tn_mall_responsable_produit_searchProd:
    path:     /user-responsable/products/searchProd/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:Responsable:searchProd}


condors_tn_mall_simpleUser_produit_searchProdOrder:
    path:     /brands/mini-website/{id}/products/searchProdOrder/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:searchProdSimpleOrder}
    requirements:
        id: \d+


    
#Brands

condors_tn_mall_responsable_brands:
    path:     /user-responsable/brands
    defaults: { _controller: CondorsTnMallBundle:Responsable:brands}
    
    
condors_tn_mall_simple_brands:
    path:     /brands
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:brands}
    
condors_tn_mall_simple_brands_special:
    path:     /brands/mini-website/{id}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:brandsSpec}
    requirements:
        id: \d+

#Categories

condors_tn_mall_responsable_categories:
    path:     /user-responsable/categories
    defaults: { _controller: CondorsTnMallBundle:Responsable:categories}

condors_tn_mall_responsable_categories_update_pos:
    path:     /user-responsable/categories/update/{id}/{pos}
    defaults: { _controller: CondorsTnMallBundle:Responsable:updateCatPosition}


condors_tn_mall_simple_categories_searchCategories:
    path:     /categories/search-categories/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:Responsable:searchCategorie}
    requirements:
        txtSearch: \d+

condors_tn_mall_check-google:
    path:     /login/check-google
    defaults: { _controller: CondorsTnMallBundle:Responsable:checkGoogle}
