condors_tn_mall_homepageNewProd:
    path:     /
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:showNewProduct }

condors_tn_mall_about:
    path:     /about
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:showAbout }

condors_tn_mall_test:
    path:     /test
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:showtest }

condors_tn_mall_faq:
    path:     /faq
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:showFaq }
  
condors_tn_mall_shopDetail:
    path:     /shop-Detail/{id}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:shopDetail }
    requirements:
        id: \d+

condors_tn_mall_account:
    path:     /
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:UserConnect}

condors_tn_mall_pro_regsitration:
    path:     /responsable/register
    defaults: { _controller: CondorsTnMallBundle:Registration:registerBrand}
 
condors_tn_mall_regsitration:
    path:     /register
    defaults: { _controller: CondorsTnMallBundle:Registration:registerUser}
    
condors_tn_mall_responsable_index:
    path:     /user-responsable/Dashboard
    defaults: { _controller: CondorsTnMallBundle:Responsable:index}

condors_tn_mall_responsable_produit:
    path:     /user-responsable/products
    defaults: { _controller: CondorsTnMallBundle:Responsable:products}
    

condors_tn_mall_responsable_produit_midifier:
    path:     /user-responsable/products/modify/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:modify}
    requirements:
        id: \d+
        
condors_tn_mall_responsable_produit_delete:
    path:     /user-responsable/products/delete/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:delete}
    requirements:
        id: \d+
   
condors_tn_mall_responsable_produit_searchProd:
    path:     /user-responsable/products/searchProd/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:Responsable:searchProd}


condors_tn_mall_simpleUser_produit_searchProdOrder:
    path:     /brands/mini-website/{id}/products/searchProdOrder/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:searchProdSimpleOrder}
    requirements:
        id: \d+

#Store_SOUHEIB

condors_tn_mall_responsable_store:
    path:     /user-responsable/stores
    defaults: { _controller: CondorsTnMallBundle:Responsable:stores}

condors_tn_mall_responsable_store_modifier:
    path:     /user-responsable/stores/modify/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:modifystore}
    requirements:
        id: \d+

condors_tn_mall_responsable_store_delete:
    path:     /user-responsable/stores/delete/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:deletestore}
    requirements:
        id: \d+

condors_tn_mall_storelocator:
    path:     /storelocator
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:storelocator }

condors_tn_mall_store_detail:
    path:     /storedetail/{id}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:storeDetail }
    requirements:
        id: \d+

condors_tn_mall_responsable_store_searchStore:
    path:     /user-responsable/stores/searchProd/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:Responsable:searchStore}

#Brands_Souheib

condors_tn_mall_responsable_brands:
    path:     /user-responsable/brands
    defaults: { _controller: CondorsTnMallBundle:Responsable:brands}

condors_tn_mall_responsable_brands_modifier:
    path:     /user-responsable/brands/modify/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:modifyBrands}
    requirements:
        id: \d+

condors_tn_mall_responsable_brands_delete:
    path:     /user-responsable/brands/delete/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:deleteBrands}
    requirements:
        id: \d+

condors_tn_mall_simple_brands_special:
    path:     /brands/mini-website/{id}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:brandsSpec}
    requirements:
        id: \d+

condors_tn_mall_simple_brands:
    path:     /brands
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:brands}

#Categories

condors_tn_mall_responsable_categories:
    path:     /user-responsable/categories
    defaults: { _controller: CondorsTnMallBundle:Responsable:categories}




condors_tn_mall_responsable_categories_update_pos:
    path:     /user-responsable/categories/update/{id}/{pos}
    defaults: { _controller: CondorsTnMallBundle:Responsable:updateCatPosition}


condors_tn_mall_simple_categories_searchCategories:
    path:     /categories/search-categories/{txtSearch}
    defaults: { _controller: CondorsTnMallBundle:Responsable:searchCategorie}
    requirements:
        txtSearch: \d+

condors_tn_mall_add_Panier:
    path:     /AddPanier/{id}
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:AddPanier }
    requirements:
        id: \d+

condors_tn_mall_show_Panier:
    path:     /Panier
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:ShowPanier }

condors_tn_mall_payment:
    path:     /user/payments/
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:payment }

canceledPayment:
    path:     /canceledPayment
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:canceledPayment }

completedPayment:
    path:     /completedPayment
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:completedPayment }


condors_tn_mall_check-google:
    path:     /login/check-google
    defaults: { _controller: CondorsTnMallBundle:Responsable:checkGoogle}
    
condors_tn_mall_check-facebook:
    path:     /login/check-facebook
    defaults: { _controller: CondorsTnMallBundle:Responsable:checkFacebook}
    
  #AMIN SECTION DON'T TOUCH OR I'LL KILL YOU! 
  
condors_tn_mall_responsable_categories_update_pos:
    path:     /user-responsable/categories/update/{id}/{pos}
    defaults: { _controller: CondorsTnMallBundle:Responsable:updateCatPosition}
  
condors_tn_mall_Admin_index:
    path:     /admin
    defaults: { _controller: CondorsTnMallBundle:Admin:index }
    
condors_tn_mall_Admin_GestionPack:
    path:     /admin/pack
    defaults: { _controller: CondorsTnMallBundle:Admin:gestionPack }
    
condors_tn_mall_Admin_addPack:
    path:     /admin/pack/add
    defaults: { _controller: CondorsTnMallBundle:Admin:addPack }

condors_tn_mall_Admin_modifyPack:
    path:     /admin/pack/modify/{id}
    defaults: { _controller: CondorsTnMallBundle:Admin:modifyPack }

condors_tn_mall_Admin_displayPacks:
    path:     /admin/pack/display
    defaults: { _controller: CondorsTnMallBundle:Admin:displayPacks }

condors_tn_mall_Admin_removePacks:
    path:     /admin/pack/remove/{id}
    defaults: { _controller: CondorsTnMallBundle:Admin:removePack }

condors_tn_mall_Admin_test:
    path:     /test
    defaults: { _controller: CondorsTnMallBundle:Admin:test }
    
condors_tn_mall_responsable_displayBouthPacks:
    path:     /user-responsable/displayBoughtPacks
    defaults: { _controller: CondorsTnMallBundle:Responsable:displayBouthPacks}
    
condors_tn_mall_responsable_GestionPack:
    path:     /user-responsable/managePacks
    defaults: { _controller: CondorsTnMallBundle:Responsable:gestionPack }
    
condors_tn_mall_responsable_buyPack:
    path:     /user-responsable/buyPacks/{id}
    defaults: { _controller: CondorsTnMallBundle:Responsable:buyPacks }
 
 
condors_tn_mall_packAProduits:
    path:     /packAProduitsA
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:pubPackA }
    
condors_tn_mall_packBProduits:
    path:     /packAProduitsB
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:pubPackB }

condors_tn_mall_packCProduits:
    path:     /packAProduitsC
    defaults: { _controller: CondorsTnMallBundle:SimpleVisitor:pubPackC }
 #END AMIN YOU CAN TOUCH EVERY THING AFTER HERE !


condors_tn_mall_chart:
    path:     /user-responsable/chart
    defaults: { _controller: CondorsTnMallBundle:Responsable:chart }

condors_tn_mall_chartPie:
    path:     /user-responsable/chartPie
    defaults: { _controller: CondorsTnMallBundle:Responsable:chartPie }

condors_tn_mall_Admin_mall_chat:
    path:     /admin/mall-chat
    defaults: { _controller: CondorsTnMallBundle:Admin:chat }