services:
  redirect.after.login:
    class: Condors\TnMallBundle\Redirection\AfterLoginRedirection
    arguments: [@router]

  app.provider.oauth:
    class: Condors\TnMallBundle\Security\Core\User\OAuthUserProvider
    arguments: [@fos_user.user_manager,{facebook: facebookID, google: googleID}]

        