imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@CondorsTnMallBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Condors\TnMallBundle\Entity\User
    registration:
        confirmation:
            enabled: true


fos_comment:
    db_driver: orm
    class:
        model:
            comment: Condors\TnMallBundle\Entity\Comment
            thread: Condors\TnMallBundle\Entity\Thread
            vote: Condors\TnMallBundle\Entity\Vote

    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl

    acl_roles:
        comment:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_RESPONSABLE
            delete: ROLE_RESPONSABLE
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_RESPONSABLE
            delete: ROLE_RESPONSABLE
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_RESPONSABLE
            delete: ROLE_RESPONSABLE
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    bundles: [ "FOSCommentBundle","CondorsTnMallBundle" ]


dcs_rating:
    db_driver: orm
    base_path_to_redirect: / # when the permalink is not configured
    max_value: 5 # maximum value for the vote (stars displayed)
    model:
        rating: Condors\TnMallBundle\Entity\Rating
        vote: Condors\TnMallBundle\Entity\Voter
    
    
nomaya_social:
    buttons:
        facebook:
            url:   "https://www.facebook.com/profile.php?id=968136899926841&fref=ts"
            locale: "fr_FR"
            send: false 
            width : 300 
            showFaces : false
            layout : "button_count"
    theme :  'default' 
    

hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    connect:
        account_connector: app.provider.oauth
    http_client:
         verify_peer: false
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "1063807953689472"
            client_secret:       "9ab1a49ec601ca54ebdee65767aea8e6"
            scope:               "email, public_profile"
            infos_url:           "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            paths:
                email: email
            options:
                display: page
        google:
            type:                google
            client_id:           "758254943927-jtu7q4u4u4d4l7et56cntqrlg92kqkjc.apps.googleusercontent.com"
            client_secret:       "8u2-heMsWbOTl86T-VoKhCvj"
            scope:              "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email: email

beelab_paypal:
    return_route: completedPayment
    cancel_route: canceledPayment
    test_mode:    "%kernel.debug%"
    username:  "TunisiaMall_api1.tunisiamall.com"
    password:  "ZUCHAY988YSQKYV9"
    signature: "AFcWxV21C7fd0v3bYYYRCpSSRl31ApxapTSdZmXXYQseVZRhenhkChFO"
gregwar_captcha: ~

mremi_contact:
    store_data:            false
    contact_class:         Mremi\ContactBundle\Model\Contact

    form:
        type:              mremi_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop

    email:
        mailer:            mremi_contact.mailer.twig_swift
        from:
            - { address: john.doe@example.com, name: "John Doe" }
            - { address: foo.bar@example.com }
        to:
            - { address: selmi.souheib@gmail.com, name: "Webmaster" }
            - { address: selmi.souheib@gmail.com }

        template:          MremiContactBundle:Contact:email.txt.twig

endroid_qr_code:
    size: 100
    padding: 10
    extension: gif
    error_correction_level: high
    foreground_color: { r: 0, g: 0, b: 0, a: 0 }
    background_color: { r: 255, g: 255, b: 255, a: 0 }
    label: "My label"
    label_font_size: 16

knp_snappy:
    pdf:
        enabled:    true
        binary:     wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        options:
          print-media-type: true
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
        options:    []






