Condors\TnMallBundle\Entity\Achatpack:
    type: entity
    table: achatpack
    indexes:
        idResponsable:
            columns:
                - idResponsable
                - idPack
        idPack:
            columns:
                - idPack
        IDX_324C3F5C120FF27F:
            columns:
                - idResponsable
    id:
        idachat:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: idAchat
            generator:
                strategy: IDENTITY
    fields:
        dateachat:
            type: date
            nullable: false
            column: dateAchat
    manyToOne:
        idresponsable:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idResponsable:
                    referencedColumnName: id
            orphanRemoval: false
        idpack:
            targetEntity: Pack
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idPack:
                    referencedColumnName: id_pack
            orphanRemoval: false
    lifecycleCallbacks: {  }
