Condors\TnMallBundle\Entity\Enseigne:
    type: entity
    table: enseigne
    indexes:
        id_enseigne:
            columns:
                - id_enseigne
        id_responsable_enseigne:
            columns:
                - libelleEnseigne
        id_responsable_enseigne_2:
            columns:
                - idResponsableEnseigne
        id_enseigne_2:
            columns:
                - id_enseigne
        id_enseigne_3:
            columns:
                - id_enseigne
    id:
        idEnseigne:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_enseigne
            generator:
                strategy: IDENTITY
    fields:
        libelleenseigne:
            type: string
            nullable: false
            length: 15
            fixed: false
            column: libelleEnseigne
        descriptionenseigne:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: descriptionEnseigne
        imageenseigne:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: imageEnseigne
    manyToOne:
        idresponsableenseigne:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idResponsableEnseigne:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
