Condors\TnMallBundle\Entity\Lignepaniercommande:
    type: entity
    table: lignepaniercommande
    indexes:
        id_ligne:
            columns:
                - id_ligne
        id_panier:
            columns:
                - id_panier
        id_commande:
            columns:
                - id_commande
        id_produit:
            columns:
                - id_produit
        id_panier_2:
            columns:
                - id_panier
    id:
        idLigne:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_ligne
            generator:
                strategy: IDENTITY
    fields:
        idPanier:
            type: integer
            nullable: true
            unsigned: false
            column: id_panier
        idCommande:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: id_commande
        idProduit:
            type: integer
            nullable: false
            unsigned: false
            column: id_produit
    lifecycleCallbacks: {  }
