Condors\TnMallBundle\Entity\Pack:
    type: entity
    table: pack
    indexes:
        id_pack:
            columns:
                - id_pack
        id_pack_2:
            columns:
                - id_pack
    id:
        idPack:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_pack
            generator:
                strategy: IDENTITY
    fields:
        zoneA:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: Zone_A
        zoneB:
            type: boolean
            nullable: false
            default: '0'
            column: Zone_B
        zoneC:
            type: boolean
            nullable: false
            default: '0'
            column: Zone_C
        algo1:
            type: boolean
            nullable: false
            default: '0'
            column: ALGO_1
        algo2:
            type: boolean
            nullable: false
            default: '0'
            column: ALGO_2
        algo3:
            type: boolean
            nullable: false
            default: '0'
            column: ALGO_3
        libelle:
            type: string
            nullable: true
            length: 255
            fixed: false
            default: '0'
            column: Libelle
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
