Condors\TnMallBundle\Entity\Paiement:
    type: entity
    table: paiement
    indexes:
        id_commande:
            columns:
                - id_commande
    id:
        idPaiement:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_paiement
            generator:
                strategy: IDENTITY
    fields:
        idCommande:
            type: integer
            nullable: false
            unsigned: false
            column: id_commande
    lifecycleCallbacks: {  }
