Condors\TnMallBundle\Entity\Produit:
    type: entity
    table: produit
    indexes:
        id_produit:
            columns:
                - id_produit
        id_catalogue:
            columns:
                - id_catalogue
        id_produit_2:
            columns:
                - id_produit
                - id_catalogue
        id_promotion:
            columns:
                - id_promotion
    id:
        idProduit:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_produit
            generator:
                strategy: IDENTITY
    fields:
        idPromotion:
            type: integer
            nullable: true
            unsigned: false
            column: id_promotion
        libelleProduit:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: libelle_produit
        categorieProduit:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: categorie_produit
        refProduit:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: ref_produit
        descriptionProduit:
            type: text
            nullable: false
            length: 65535
            fixed: false
            column: description_produit
        tvaProduit:
            type: integer
            nullable: false
            unsigned: false
            column: tva_produit
        prixProduit:
            type: integer
            nullable: false
            unsigned: false
            column: prix_produit
        imageprodfront:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: imageProdFront
        imageprodback:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: imageProdBack
        imageprodreel:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: imageProdReel
        datecreation:
            type: datetime
            nullable: true
            column: dateCreation
    manyToOne:
        idCatalogue:
            targetEntity: Catalogue
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_catalogue:
                    referencedColumnName: id_catalogue
            orphanRemoval: false
    lifecycleCallbacks: {  }
