Condors\TnMallBundle\Entity\Recevoir:
    type: entity
    table: recevoir
    indexes:
        id_recevoir:
            columns:
                - id_recevoir
                - id_suivre
                - id_notification
        id_suivre:
            columns:
                - id_suivre
                - id_notification
        id_notification:
            columns:
                - id_notification
    id:
        idRecevoir:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_recevoir
            generator:
                strategy: IDENTITY
    fields:
        idSuivre:
            type: integer
            nullable: false
            unsigned: false
            column: id_suivre
        idNotification:
            type: integer
            nullable: false
            unsigned: false
            column: id_notification
        vu:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
