Condors\TnMallBundle\Entity\Stock:
    type: entity
    table: stock
    indexes:
        id_stock:
            columns:
                - id_stock
                - id_boutique
                - id_produit
        id_boutique:
            columns:
                - id_boutique
                - id_produit
        id_produit:
            columns:
                - id_produit
    id:
        idStock:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_stock
            generator:
                strategy: IDENTITY
    fields:
        idBoutique:
            type: integer
            nullable: false
            unsigned: false
            column: id_boutique
        idProduit:
            type: integer
            nullable: false
            unsigned: false
            column: id_produit
    lifecycleCallbacks: {  }
