Condors\TnMallBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        UNIQ_8D93D64992FC23A8:
            columns:
                - username_canonical
        UNIQ_8D93D649A0D96FBF:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 255
            fixed: false
        usernameCanonical:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: username_canonical
        email:
            type: string
            nullable: true
            length: 255
            fixed: false
        emailCanonical:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: true
        salt:
            type: string
            nullable: true
            length: 255
            fixed: false
        password:
            type: string
            nullable: true
            length: 255
            fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        locked:
            type: boolean
            nullable: true
        expired:
            type: boolean
            nullable: true
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: true
            length: null
            fixed: false
        credentialsExpired:
            type: boolean
            nullable: true
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at
        cin:
            type: string
            nullable: true
            length: 30
            fixed: false
        nom:
            type: string
            nullable: true
            length: 30
            fixed: false
        prenom:
            type: string
            nullable: true
            length: 30
            fixed: false
        sexe:
            type: string
            nullable: true
            length: 30
            fixed: false
        anniversaire:
            type: date
            nullable: true
            column: Anniversaire
        telephone:
            type: integer
            nullable: true
            unsigned: false
        adresse:
            type: string
            nullable: true
            length: 30
            fixed: false
        image:
            type: string
            nullable: true
            length: 255
            fixed: false
        idEnseigne:
            type: integer
            nullable: true
            unsigned: false
            column: id_enseigne
        attente:
            type: boolean
            nullable: true
        bloquer:
            type: boolean
            nullable: true
        supprimer:
            type: boolean
            nullable: true
        facebookId:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: facebook_id
        googleId:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: google_id
    lifecycleCallbacks: {  }
